# import = ['~/.config/alacritty/themes/tokyonight-moon-nvim.toml']
import = ['~/.config/alacritty/themes/cubiq-emerald-night.toml']
# import = ['~/.config/alacritty/themes/tokyo-night.toml']

[window]
# Options: Windowed, Maximized, Fullscreen, SimpleFullscreen
startup_mode = "Maximized"
opacity = 0.9
blur = true

[font]
# normal.family = "MesloLGS Nerd Font Mono"
size = 11

[keyboard]
bindings = [
    { key = "Right", mods = "Alt", chars = "\u001BF" },
    { key = "Left", mods = "Alt", chars = "\u001BB" },
]
